/**
 * Auto-generated by scripts/fetch_unsplash.mjs
 * Do not edit manually — re-run the script to refresh images.
 *
 * Attribution: Unsplash License — free to use, credit appreciated.
 * Per Unsplash guidelines: "Photo by [name] on Unsplash" in alt / caption.
 */

export type UnsplashImage = {
  src: string;
  alt: string;
  credit: { name: string; url: string; photoUrl: string };
  width: number;
  height: number;
};

export const unsplashImages = {
  "race-action": {
    "src": "/images/unsplash/race-action.jpg",
    "alt": "a group of people riding on the backs of horses",
    "credit": {
      "name": "2H Media",
      "url": "https://unsplash.com/@2hmedia",
      "photoUrl": "https://unsplash.com/photos/a-group-of-people-riding-on-the-backs-of-horses-ndOK4D5VcaQ"
    },
    "width": 4240,
    "height": 2384
  },
  "racecourse-aerial": {
    "src": "/images/unsplash/racecourse-aerial.jpg",
    "alt": "crowd near building",
    "credit": {
      "name": "Annie Spratt",
      "url": "https://unsplash.com/@anniespratt",
      "photoUrl": "https://unsplash.com/photos/crowd-near-building-G8NEver_oYA"
    },
    "width": 5761,
    "height": 3841
  },
  "crowd-stands": {
    "src": "/images/unsplash/crowd-stands.jpg",
    "alt": "people watching horse race at daytime",
    "credit": {
      "name": "Katee Lue",
      "url": "https://unsplash.com/@kateelue",
      "photoUrl": "https://unsplash.com/photos/people-watching-horse-race-at-daytime-xSe27sPGGxA"
    },
    "width": 5184,
    "height": 3456
  },
  "data-screen": {
    "src": "/images/unsplash/data-screen.jpg",
    "alt": "Computer screen displaying lines of code",
    "credit": {
      "name": "Jakub Żerdzicki",
      "url": "https://unsplash.com/@jakubzerdzicki",
      "photoUrl": "https://unsplash.com/photos/computer-screen-displaying-lines-of-code-n3ba57RKVNs"
    },
    "width": 3840,
    "height": 2160
  },
  "hk-city-night": {
    "src": "/images/unsplash/hk-city-night.jpg",
    "alt": "aerial photography of concrete city buildings",
    "credit": {
      "name": "Natalya Letunova",
      "url": "https://unsplash.com/@naletu",
      "photoUrl": "https://unsplash.com/photos/aerial-photography-of-concrete-city-buildings-lZXyGjsRnP0"
    },
    "width": 4608,
    "height": 3456
  },
  "horse-detail": {
    "src": "/images/unsplash/horse-detail.jpg",
    "alt": "brow horse",
    "credit": {
      "name": "Sunnie-Lee Davison",
      "url": "https://unsplash.com/@sunnielee",
      "photoUrl": "https://unsplash.com/photos/brow-horse-mQEOPaSzBI4"
    },
    "width": 5184,
    "height": 3456
  }
} as const satisfies Record<string, UnsplashImage>;

export type ImageKey = keyof typeof unsplashImages;
